# Generated by Django 2.2.1 on 2019-05-31 00:28

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('states', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(default=None)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326)),
                ('desc', models.TextField(default=None)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VisitorCenters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(default=None, max_length=200)),
                ('desc', models.TextField(default=None)),
                ('directions', models.TextField(default=None)),
                ('direction_url', models.CharField(default=None, max_length=200)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326)),
                ('park', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parks.Park')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(default=None, max_length=200)),
                ('desc', models.TextField(null=True)),
                ('img', models.CharField(default=None, max_length=200)),
                ('park', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parks.Park')),
            ],
            options={
                'ordering': ('park',),
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(default=None, max_length=200)),
                ('desc', models.TextField(null=True)),
                ('img', models.CharField(default=None, max_length=200)),
                ('park', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parks.Park')),
            ],
            options={
                'ordering': ('park',),
            },
        ),
        migrations.CreateModel(
            name='NewsReleases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(default=None, max_length=200)),
                ('img', models.CharField(default=None, max_length=200)),
                ('abstract', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('park', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parks.Park')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='LessonPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(default=None, max_length=200)),
                ('duration', models.IntegerField(null=True)),
                ('desc', models.TextField(null=True)),
                ('subject', models.CharField(max_length=255)),
                ('grade_level', models.CharField(max_length=255)),
                ('park', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parks.Park')),
            ],
            options={
                'ordering': ('park',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_start', models.DateField(null=True)),
                ('date_end', models.DateField(null=True)),
                ('times', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None)),
                ('desc', models.TextField(null=True)),
                ('reg_required', models.BooleanField(null=True)),
                ('reg_info', models.TextField(null=True)),
                ('park', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parks.Park')),
            ],
            options={
                'ordering': ('date_start',),
            },
        ),
        migrations.CreateModel(
            name='Campgrounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reserve_url', models.CharField(default=None, max_length=200)),
                ('desc', models.TextField(default=None)),
                ('reg_overview', models.TextField(default=None)),
                ('weather', models.TextField(default=None)),
                ('campsites', models.IntegerField(blank=True, default=0)),
                ('internet_info', models.TextField(default=None)),
                ('rv_info', models.TextField(default=None)),
                ('ada_info', models.TextField(default=None)),
                ('wheelchair_info', models.TextField(default=None)),
                ('cell_info', models.TextField(default=None)),
                ('additional_info', models.TextField(default=None)),
                ('firewood', models.BooleanField(blank=True, default=None)),
                ('ice', models.BooleanField(blank=True, default=None)),
                ('food_storage', models.BooleanField(blank=True, default=None)),
                ('internet', models.BooleanField(blank=True, default=None)),
                ('cellphone', models.BooleanField(blank=True, default=None)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326)),
                ('park', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parks.Park')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(default=None, max_length=200)),
                ('img', models.CharField(default=None, max_length=200)),
                ('desc', models.TextField(null=True)),
                ('park', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parks.Park')),
            ],
            options={
                'ordering': ('park',),
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField(null=True)),
                ('url', models.CharField(default=None, max_length=200)),
                ('park', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parks.Park')),
            ],
            options={
                'ordering': ('park',),
            },
        ),
    ]
