# Generated by Django 2.2.2 on 2019-06-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='designation',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
